codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: auto
        threshold: 1%
      unit_api:
        target: auto
        threshold: 1%
        flags:
          - unit-api
      integration_dragonfly:
        target: auto
        threshold: 1%
        flags:
          - integration-dragonfly
      integration_typesense:
        target: auto
        threshold: 1%
        flags:
          - integration-typesense
    patch:
      default:
        target: 85%
        threshold: 1%

flags:
  unit-api:
    carryforward: true
  integration-dragonfly:
    carryforward: true
  integration-typesense:
    carryforward: true

comment: false
